### ISSUE TITLE
email-text causes problem in translated content

### ISSUE THREAD

**Issue by JoniRousu** [Jezzamonn/fourier#10]
Just noticed that in both translations (german and spanish) in the second to last paragraph the span "email-text" inserts english text ("email me at ...@..., or"). Can this be fixed by special span ids for each language or by editing the inserted text to be just your email address? 
Also "homepage" is capitalsed in german.

**Comment by Jezzamonn** [comment]
Ah, you're right, good catch.

I didn't want to directly embed the email due to spambot type things, but yeah it doesn't work properly when you deal with other translations. The reason it's set up the way it is at the moment is to make it so if you're viewing the page without JavaScript it still reads normally.

Let me think about the best way to set this up to deal with this and get back to you

**Comment by Jezzamonn** [comment]
Fixed in 
https://github.com/Jezzamonn/fourier/commit/24ae85ba3b06f27a7b92d9499cf09e5d7d9f922b, along with a few other commits! Thanks for flagging the issue!
